name: dartnow
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  browser: '^0.10.0'
  github: ">=2.2.3 <3.0.0"
  yaml: "^2.1.3"
  firebase:
    git:
      url: https://github.com/kasperpeulen/firebase-dart
      ref: onAuth
  intl: '^0.12.4'
  route_hierarchical: '^0.6.2'
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter