name: dartnow
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  mdl: '^1.3.2'
  di: '^3.3.4'
  github: '^2.2.3+1'
  firebase: '^0.6.2'
  browser: '^0.10.0'
  github: ">=2.2.3 <3.0.0"
  yaml: "^2.1.3"
  intl: any
  route_hierarchical: '^0.6.2'
  dart_to_js_script_rewriter: any
transformers:
  - di
  - dart_to_js_script_rewriter